### PR TITLE
Update compat.yaml

### PR DESCRIPTION
**Pull request by krlsdu**
Update deprecated tag sudo: yes to become: true

### CODE REVIEW

**Comment by krlsdu** [comment]
The test fail because the version of ansible install is old, maybe update is a good approach.
see the list ansible versions maintenance.
[releases and maintanence](http://docs.ansible.com/ansible/latest/release_and_maintenance.html#release-status)

**Comment by wtanaka** [comment]
@krlsdu thanks for the contribution.  among other things, the test script needed [updating](https://github.com/wtanaka/role-tester-ansible/compare/14d33e1...5d8112e) and this was a good prompt to do that.

Are you aware of any way to do a conditional include in Ansible without evaluating the included file?  Unfortunately I can't seem to find an approach to use "become" that maintains compatibility across many ansible versions, as it seems like ansible wasn't designed to be forward compatible.

The best approach I was able to find was to run sudo explicitly.  I'll see if I can do it here.  I'm going to close this for now, but if you find an approach that passes the tests, please definitely post it and reopen this!

**Comment by wtanaka** [comment]
[2.2.3.0 support](https://github.com/wtanaka/ansible-role-vim/pull/19)

**Comment by krlsdu** [comment]
I understand your concern.
My point of view, is it really necessary to maintain compatibility with such older versions?
I think not, because either someone uses ansible 1.X or 2.1.X he suffers a bigger problem, the unsupported.

So the efforts to make the test for your roles, to support those versions is unnecessary.

Yes, it does not solve the problem related to "sudo" and "become", but it minimizes the test time and effort to think when new conditions for test code evolution are created.

**Comment by wtanaka** [comment]
@krlsdu this might work for you https://github.com/wtanaka/ansible-role-vim/pull/20

**Pull request closed without merging**
